//! Hybrid deterministic retrieval over project manifests.

use std::collections::{BTreeMap, BTreeSet};

use crate::lexical::{LexicalIndex, documents_from_manifest};
use crate::types::{
    ProjectManifest, RerankCandidate, RetrievalQuery, RetrievalResult, RetrievalScoringPlan,
    RetrievalScoringWeights, VectorQuery,
};
use crate::vector::{Reranker, VectorIndex};

/// Retrieves project model results using exact path, exact symbol, lexical, and
/// graph expansion scoring.
///
/// # Arguments
///
/// * `manifest` - Indexed project manifest.
/// * `query` - Retrieval query.
pub fn retrieve(manifest: &ProjectManifest, query: &RetrievalQuery) -> Vec<RetrievalResult> {
    retrieve_with_boundaries::<
        crate::vector::DeterministicVectorIndex,
        crate::vector::DeterministicReranker,
    >(
        manifest,
        query,
        None,
        None,
        None,
        &RetrievalScoringWeights::default(),
    )
}

/// Plans retrieval phases from query content and optional integration boundaries.
///
/// # Arguments
///
/// * `query` - Retrieval query whose exact/text/graph flags drive phases.
/// * `has_vector_query` - Whether an embedding query is available.
/// * `has_vector_index` - Whether a vector index boundary is available.
/// * `has_reranker` - Whether a reranker boundary is available.
pub fn plan_retrieval(
    query: &RetrievalQuery,
    has_vector_query: bool,
    has_vector_index: bool,
    has_reranker: bool,
) -> RetrievalScoringPlan {
    let has_text = query
        .text
        .as_deref()
        .is_some_and(|text| !text.trim().is_empty());
    RetrievalScoringPlan {
        exact: query.path.is_some() || query.symbol.is_some(),
        lexical: has_text,
        vector: has_vector_query && has_vector_index,
        graph: query.include_graph_expansion,
        rerank: has_text && has_reranker,
    }
}

/// Retrieves project model results with optional vector and reranker
/// integrations.
///
/// The crate defines the typed boundary and deterministic test implementations;
/// production embedding providers are external integrations that pass
/// precomputed vectors through this API.
///
/// # Arguments
///
/// * `manifest` - Indexed project manifest.
/// * `query` - Retrieval query.
/// * `vector_query` - Optional provider-neutral embedding generated by an
///   external integration.
/// * `vector_index` - Optional vector index implementation.
/// * `reranker` - Optional reranker implementation.
/// * `weights` - Typed scoring weights used by the planner.
pub fn retrieve_with_boundaries<V, R>(
    manifest: &ProjectManifest,
    query: &RetrievalQuery,
    vector_query: Option<&VectorQuery>,
    vector_index: Option<&V>,
    reranker: Option<&R>,
    weights: &RetrievalScoringWeights,
) -> Vec<RetrievalResult>
where
    V: VectorIndex,
    R: Reranker,
{
    if weights.validate().is_err() {
        return Vec::new();
    }
    let limit = if query.limit == 0 { 10 } else { query.limit };
    let plan = plan_retrieval(
        query,
        vector_query.is_some(),
        vector_index.is_some(),
        reranker.is_some(),
    );
    let mut results = if plan.exact {
        exact_results(manifest, query, weights)
    } else {
        BTreeMap::new()
    };
    retain_path_scope(&mut results, query);

    if plan.lexical
        && let Some(text) = &query.text
    {
        let lexical_index = LexicalIndex::from_manifest(manifest);
        for hit in lexical_index.search(text) {
            if !matches_path_scope(&hit.path, query) {
                continue;
            }
            merge_part(
                &mut results,
                hit.id,
                hit.path,
                hit.symbol,
                "lexical",
                hit.score * weights.lexical,
                hit.provenance,
            );
        }
    }

    if plan.vector
        && let (Some(vector_query), Some(vector_index)) = (vector_query, vector_index)
    {
        for hit in vector_index.search(vector_query) {
            if let Some((path, symbol, provenance)) = manifest_result_surface(manifest, &hit.id) {
                if !matches_path_scope(&path, query) {
                    continue;
                }
                merge_part(
                    &mut results,
                    hit.id,
                    path,
                    symbol,
                    "vector",
                    hit.score * weights.vector,
                    provenance,
                );
            }
        }
    }

    if plan.graph {
        expand_graph(manifest, query, &mut results, weights);
    }

    if plan.rerank
        && let (Some(text), Some(reranker)) = (&query.text, reranker)
    {
        let candidates = rerank_candidates(manifest, &results);
        for score in reranker.rerank(text, &candidates) {
            if let Some(result) = results.get_mut(&score.id) {
                result
                    .score_parts
                    .insert("rerank".to_string(), score.score * weights.rerank);
                result.score = result.score_parts.values().sum();
            }
        }
    }

    let mut values = results.into_values().collect::<Vec<_>>();
    values.sort_by(|left, right| {
        right
            .score
            .total_cmp(&left.score)
            .then_with(|| left.id.cmp(&right.id))
    });
    values.truncate(limit);
    values
}

fn retain_path_scope(results: &mut BTreeMap<String, RetrievalResult>, query: &RetrievalQuery) {
    results.retain(|_, result| matches_path_scope(&result.path, query));
}

fn matches_path_scope(path: &str, query: &RetrievalQuery) -> bool {
    let exact_path_matches = query
        .path
        .as_deref()
        .is_none_or(|exact_path| path == exact_path);
    let prefix_matches = query
        .path_prefix
        .as_deref()
        .is_none_or(|prefix| path.starts_with(prefix));
    exact_path_matches && prefix_matches
}

fn exact_results(
    manifest: &ProjectManifest,
    query: &RetrievalQuery,
    weights: &RetrievalScoringWeights,
) -> BTreeMap<String, RetrievalResult> {
    let mut results = BTreeMap::new();
    for file in &manifest.files {
        if query.path.as_deref() == Some(file.path.as_str()) {
            merge_part(
                &mut results,
                file.path.clone(),
                file.path.clone(),
                None,
                "exact_path",
                weights.exact_path,
                file.provenance.clone(),
            );
        }
    }
    for symbol in &manifest.symbols {
        if query.symbol.as_deref() == Some(symbol.name.as_str())
            || query.symbol.as_deref() == Some(symbol.id.as_str())
        {
            merge_part(
                &mut results,
                symbol.id.clone(),
                symbol.path.clone(),
                Some(symbol.name.clone()),
                "exact_symbol",
                weights.exact_symbol,
                symbol.provenance.clone(),
            );
        }
    }
    results
}

fn merge_part(
    results: &mut BTreeMap<String, RetrievalResult>,
    id: String,
    path: String,
    symbol: Option<String>,
    part: &str,
    score: f32,
    provenance: crate::types::Provenance,
) {
    let result = results
        .entry(id.clone())
        .or_insert_with(|| RetrievalResult {
            id,
            path,
            symbol,
            score: 0.0,
            score_parts: BTreeMap::new(),
            provenance,
        });
    result.score_parts.insert(part.to_string(), score);
    result.score = result.score_parts.values().sum();
}

fn expand_graph(
    manifest: &ProjectManifest,
    query: &RetrievalQuery,
    results: &mut BTreeMap<String, RetrievalResult>,
    weights: &RetrievalScoringWeights,
) {
    let seeds = results.keys().cloned().collect::<BTreeSet<_>>();
    for graph_edge in &manifest.edges {
        if seeds.contains(&graph_edge.from) || seeds.contains(&graph_edge.to) {
            let id = if seeds.contains(&graph_edge.from) {
                graph_edge.to.clone()
            } else {
                graph_edge.from.clone()
            };
            if let Some((path, symbol, provenance)) = manifest_result_surface(manifest, &id) {
                if !matches_path_scope(&path, query) {
                    continue;
                }
                merge_part(
                    results,
                    id,
                    path,
                    symbol,
                    "graph",
                    graph_edge.confidence * weights.graph,
                    provenance,
                );
            }
        }
    }
}

fn manifest_result_surface(
    manifest: &ProjectManifest,
    id: &str,
) -> Option<(String, Option<String>, crate::types::Provenance)> {
    manifest
        .symbols
        .iter()
        .find(|symbol| symbol.id == id)
        .map(|symbol| {
            (
                symbol.path.clone(),
                Some(symbol.name.clone()),
                symbol.provenance.clone(),
            )
        })
        .or_else(|| {
            manifest
                .files
                .iter()
                .find(|file| file.path == id)
                .map(|file| (file.path.clone(), None, file.provenance.clone()))
        })
        .or_else(|| {
            manifest
                .shards
                .iter()
                .find(|shard| shard.id == id)
                .map(|shard| (shard.path.clone(), None, shard.provenance.clone()))
        })
}

fn rerank_candidates(
    manifest: &ProjectManifest,
    results: &BTreeMap<String, RetrievalResult>,
) -> Vec<RerankCandidate> {
    let documents = documents_from_manifest(manifest)
        .into_iter()
        .map(|document| (document.id.clone(), document.text))
        .collect::<BTreeMap<_, _>>();
    results
        .keys()
        .map(|id| RerankCandidate {
            id: id.clone(),
            text: documents.get(id).cloned().unwrap_or_else(|| id.clone()),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use pretty_assertions::assert_eq;

    use super::*;
    use crate::ProjectIndexer;
    use crate::indexer::tests::fixture_project;
    use crate::vector::{DeterministicReranker, DeterministicVectorIndex};

    #[test]
    fn content_only_query_returns_source_body_shard() -> Result<()> {
        let fixture = tempfile::TempDir::new()?;
        let root = fixture.path().join("project");
        std::fs::create_dir_all(root.join("src"))?;
        std::fs::write(
            root.join("src").join("only.rs"),
            "pub fn ordinary_name() -> &'static str {\n    \"bodyonlyneedle\"\n}\n",
        )?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("bodyonlyneedle".to_string()),
            path: None,
            path_prefix: None,
            symbol: None,
            limit: 3,
            include_graph_expansion: false,
        };

        let actual = retrieve(&manifest, &query);
        let expected = Some(("src/only.rs".to_string(), Some(1), Some(3)));
        assert_eq!(
            actual.first().map(|result| {
                (
                    result.path.clone(),
                    result.provenance.start_line,
                    result.provenance.end_line,
                )
            }),
            expected
        );
        Ok(())
    }

    #[test]
    fn path_prefix_scope_is_applied_before_truncation() -> Result<()> {
        let fixture = tempfile::TempDir::new()?;
        let root = fixture.path().join("project");
        std::fs::create_dir_all(root.join("src").join("in"))?;
        std::fs::create_dir_all(root.join("src").join("out"))?;
        std::fs::write(
            root.join("src").join("in").join("target.rs"),
            "pub fn target() {\n    let _ = \"scopedneedle\";\n}\n",
        )?;
        std::fs::write(
            root.join("src").join("out").join("loud.rs"),
            "pub fn loud() {\n    let _ = \"scopedneedle scopedneedle scopedneedle scopedneedle scopedneedle\";\n}\n",
        )?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("scopedneedle".to_string()),
            path: None,
            path_prefix: Some("src/in/".to_string()),
            symbol: None,
            limit: 1,
            include_graph_expansion: true,
        };

        let actual = retrieve(&manifest, &query);
        let expected = vec!["src/in/target.rs".to_string()];
        assert_eq!(
            actual
                .into_iter()
                .map(|result| result.path)
                .collect::<Vec<_>>(),
            expected
        );
        Ok(())
    }

    #[test]
    fn exact_symbol_query_stays_above_body_content_hits() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("Root".to_string()),
            path: None,
            path_prefix: None,
            symbol: Some("Root".to_string()),
            limit: 1,
            include_graph_expansion: true,
        };

        let actual = retrieve(&manifest, &query);
        let expected = Some("Root".to_string());
        assert_eq!(
            actual.first().and_then(|result| result.symbol.clone()),
            expected
        );
        Ok(())
    }

    #[test]
    fn exact_path_scope_filters_lexical_results_before_truncation() -> Result<()> {
        let fixture = tempfile::TempDir::new()?;
        let root = fixture.path().join("project");
        std::fs::create_dir_all(root.join("src").join("in"))?;
        std::fs::create_dir_all(root.join("src").join("out"))?;
        std::fs::write(
            root.join("src").join("in").join("target.rs"),
            "pub fn target() {\n    let _ = \"exactneedle\";\n}\n",
        )?;
        std::fs::write(
            root.join("src").join("out").join("loud.rs"),
            "pub fn loud() {\n    let _ = \"exactneedle exactneedle exactneedle exactneedle exactneedle\";\n}\n",
        )?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("exactneedle".to_string()),
            path: Some("src/in/target.rs".to_string()),
            path_prefix: None,
            symbol: None,
            limit: 1,
            include_graph_expansion: true,
        };

        let actual = retrieve(&manifest, &query);
        let expected = vec!["src/in/target.rs".to_string()];
        assert_eq!(
            actual
                .into_iter()
                .map(|result| result.path)
                .collect::<Vec<_>>(),
            expected
        );
        Ok(())
    }

    #[test]
    fn retrieves_exact_symbol_lexical_and_graph_expansion() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("Root".to_string()),
            path: None,
            path_prefix: None,
            symbol: Some("Root".to_string()),
            limit: 5,
            include_graph_expansion: true,
        };
        let actual = retrieve(&manifest, &query);
        let expected = true;
        assert_eq!(
            actual
                .iter()
                .any(|result| result.symbol.as_deref() == Some("Root")
                    && result.score_parts.contains_key("exact_symbol")
                    && result.score_parts.contains_key("lexical")),
            expected
        );
        Ok(())
    }

    #[test]
    fn fuses_vector_and_reranker_scores_when_boundaries_are_supplied() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let root_symbol = manifest
            .symbols
            .iter()
            .find(|symbol| symbol.name == "Root")
            .expect("fixture should include Root symbol");
        let vector_index = DeterministicVectorIndex::new(BTreeMap::from([(
            root_symbol.id.clone(),
            vec![1.0, 0.0],
        )]));
        let query = RetrievalQuery {
            text: Some("Root".to_string()),
            path: None,
            path_prefix: None,
            symbol: None,
            limit: 1,
            include_graph_expansion: false,
        };
        let actual = retrieve_with_boundaries(
            &manifest,
            &query,
            Some(&VectorQuery { embedding: vec![1.0, 0.0] }),
            Some(&vector_index),
            Some(&DeterministicReranker),
            &RetrievalScoringWeights::default(),
        );
        let expected = BTreeSet::from([
            "lexical".to_string(),
            "vector".to_string(),
            "rerank".to_string(),
        ]);
        assert_eq!(
            actual
                .first()
                .map(|result| result.score_parts.keys().cloned().collect::<BTreeSet<_>>())
                .expect("retrieval should return at least one fused result"),
            expected
        );
        Ok(())
    }

    #[test]
    fn planner_enables_only_available_boundaries() {
        let setup = RetrievalQuery {
            text: Some("Root".to_string()),
            path: Some("src/lib.rs".to_string()),
            path_prefix: None,
            symbol: None,
            limit: 5,
            include_graph_expansion: true,
        };
        let actual = plan_retrieval(&setup, true, false, true);
        let expected = RetrievalScoringPlan {
            exact: true,
            lexical: true,
            vector: false,
            graph: true,
            rerank: true,
        };
        assert_eq!(actual, expected);
    }

    #[test]
    fn custom_weights_control_score_parts() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let root_symbol = manifest
            .symbols
            .iter()
            .find(|symbol| symbol.name == "Root")
            .expect("fixture should include Root symbol");
        let query = RetrievalQuery {
            text: None,
            path: None,
            path_prefix: None,
            symbol: Some("Root".to_string()),
            limit: 1,
            include_graph_expansion: false,
        };
        let weights =
            RetrievalScoringWeights { exact_symbol: 42.0, ..RetrievalScoringWeights::default() };
        let actual = retrieve_with_boundaries::<DeterministicVectorIndex, DeterministicReranker>(
            &manifest, &query, None, None, None, &weights,
        );
        let expected = Some(42.0);
        assert_eq!(
            actual
                .iter()
                .find(|result| result.id == root_symbol.id)
                .and_then(|result| result.score_parts.get("exact_symbol"))
                .copied(),
            expected,
        );
        Ok(())
    }
}
