//! Hybrid deterministic retrieval over project manifests.

use std::collections::{BTreeMap, BTreeSet};

use crate::lexical::{LexicalIndex, documents_from_manifest};
use crate::types::{
    ProjectManifest, RerankCandidate, RetrievalQuery, RetrievalResult, VectorQuery,
};
use crate::vector::{Reranker, VectorIndex};

/// Retrieves project model results using exact path, exact symbol, lexical, and
/// graph expansion scoring.
///
/// # Arguments
///
/// * `manifest` - Indexed project manifest.
/// * `query` - Retrieval query.
pub fn retrieve(manifest: &ProjectManifest, query: &RetrievalQuery) -> Vec<RetrievalResult> {
    retrieve_with_boundaries::<
        crate::vector::DeterministicVectorIndex,
        crate::vector::DeterministicReranker,
    >(manifest, query, None, None, None)
}

/// Retrieves project model results with optional vector and reranker
/// integrations.
///
/// The crate defines the typed boundary and deterministic test implementations;
/// production embedding providers are external integrations that pass
/// precomputed vectors through this API.
///
/// # Arguments
///
/// * `manifest` - Indexed project manifest.
/// * `query` - Retrieval query.
/// * `vector_query` - Optional provider-neutral embedding generated by an
///   external integration.
/// * `vector_index` - Optional vector index implementation.
/// * `reranker` - Optional reranker implementation.
pub fn retrieve_with_boundaries<V, R>(
    manifest: &ProjectManifest,
    query: &RetrievalQuery,
    vector_query: Option<&VectorQuery>,
    vector_index: Option<&V>,
    reranker: Option<&R>,
) -> Vec<RetrievalResult>
where
    V: VectorIndex,
    R: Reranker,
{
    let limit = if query.limit == 0 { 10 } else { query.limit };
    let mut results = exact_results(manifest, query);

    if let Some(text) = &query.text {
        let lexical_index = LexicalIndex::from_manifest(manifest);
        for hit in lexical_index.search(text) {
            merge_part(
                &mut results,
                hit.id,
                hit.path,
                hit.symbol,
                "lexical",
                hit.score,
                hit.provenance,
            );
        }
    }

    if let (Some(vector_query), Some(vector_index)) = (vector_query, vector_index) {
        for hit in vector_index.search(vector_query) {
            if let Some((path, symbol, provenance)) = manifest_result_surface(manifest, &hit.id) {
                merge_part(
                    &mut results,
                    hit.id,
                    path,
                    symbol,
                    "vector",
                    hit.score,
                    provenance,
                );
            }
        }
    }

    if query.include_graph_expansion {
        expand_graph(manifest, &mut results);
    }

    if let (Some(text), Some(reranker)) = (&query.text, reranker) {
        let candidates = rerank_candidates(manifest, &results);
        for score in reranker.rerank(text, &candidates) {
            if let Some(result) = results.get_mut(&score.id) {
                result.score_parts.insert("rerank".to_string(), score.score);
                result.score = result.score_parts.values().sum();
            }
        }
    }

    let mut values = results.into_values().collect::<Vec<_>>();
    values.sort_by(|left, right| {
        right
            .score
            .total_cmp(&left.score)
            .then_with(|| left.id.cmp(&right.id))
    });
    values.truncate(limit);
    values
}

fn exact_results(
    manifest: &ProjectManifest,
    query: &RetrievalQuery,
) -> BTreeMap<String, RetrievalResult> {
    let mut results = BTreeMap::new();
    for file in &manifest.files {
        if query.path.as_deref() == Some(file.path.as_str()) {
            merge_part(
                &mut results,
                file.path.clone(),
                file.path.clone(),
                None,
                "exact_path",
                100.0,
                file.provenance.clone(),
            );
        }
    }
    for symbol in &manifest.symbols {
        if query.symbol.as_deref() == Some(symbol.name.as_str())
            || query.symbol.as_deref() == Some(symbol.id.as_str())
        {
            merge_part(
                &mut results,
                symbol.id.clone(),
                symbol.path.clone(),
                Some(symbol.name.clone()),
                "exact_symbol",
                100.0,
                symbol.provenance.clone(),
            );
        }
    }
    results
}

fn merge_part(
    results: &mut BTreeMap<String, RetrievalResult>,
    id: String,
    path: String,
    symbol: Option<String>,
    part: &str,
    score: f32,
    provenance: crate::types::Provenance,
) {
    let result = results
        .entry(id.clone())
        .or_insert_with(|| RetrievalResult {
            id,
            path,
            symbol,
            score: 0.0,
            score_parts: BTreeMap::new(),
            provenance,
        });
    result.score_parts.insert(part.to_string(), score);
    result.score = result.score_parts.values().sum();
}

fn expand_graph(manifest: &ProjectManifest, results: &mut BTreeMap<String, RetrievalResult>) {
    let seeds = results.keys().cloned().collect::<BTreeSet<_>>();
    for graph_edge in &manifest.edges {
        if seeds.contains(&graph_edge.from) || seeds.contains(&graph_edge.to) {
            let id = if seeds.contains(&graph_edge.from) {
                graph_edge.to.clone()
            } else {
                graph_edge.from.clone()
            };
            if let Some((path, symbol, provenance)) = manifest_result_surface(manifest, &id) {
                merge_part(
                    results,
                    id,
                    path,
                    symbol,
                    "graph",
                    graph_edge.confidence * 10.0,
                    provenance,
                );
            }
        }
    }
}

fn manifest_result_surface(
    manifest: &ProjectManifest,
    id: &str,
) -> Option<(String, Option<String>, crate::types::Provenance)> {
    manifest
        .symbols
        .iter()
        .find(|symbol| symbol.id == id)
        .map(|symbol| {
            (
                symbol.path.clone(),
                Some(symbol.name.clone()),
                symbol.provenance.clone(),
            )
        })
        .or_else(|| {
            manifest
                .files
                .iter()
                .find(|file| file.path == id)
                .map(|file| (file.path.clone(), None, file.provenance.clone()))
        })
        .or_else(|| {
            manifest
                .shards
                .iter()
                .find(|shard| shard.id == id)
                .map(|shard| (shard.path.clone(), None, shard.provenance.clone()))
        })
}

fn rerank_candidates(
    manifest: &ProjectManifest,
    results: &BTreeMap<String, RetrievalResult>,
) -> Vec<RerankCandidate> {
    let documents = documents_from_manifest(manifest)
        .into_iter()
        .map(|document| (document.id.clone(), document.text))
        .collect::<BTreeMap<_, _>>();
    results
        .keys()
        .map(|id| RerankCandidate {
            id: id.clone(),
            text: documents.get(id).cloned().unwrap_or_else(|| id.clone()),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use pretty_assertions::assert_eq;

    use super::*;
    use crate::ProjectIndexer;
    use crate::indexer::tests::fixture_project;
    use crate::vector::{DeterministicReranker, DeterministicVectorIndex};

    #[test]
    fn retrieves_exact_symbol_lexical_and_graph_expansion() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let query = RetrievalQuery {
            text: Some("Root".to_string()),
            path: None,
            symbol: Some("Root".to_string()),
            limit: 5,
            include_graph_expansion: true,
        };
        let actual = retrieve(&manifest, &query);
        let expected = true;
        assert_eq!(
            actual
                .iter()
                .any(|result| result.symbol.as_deref() == Some("Root")
                    && result.score_parts.contains_key("exact_symbol")
                    && result.score_parts.contains_key("lexical")),
            expected
        );
        Ok(())
    }

    #[test]
    fn fuses_vector_and_reranker_scores_when_boundaries_are_supplied() -> Result<()> {
        let (fixture, root) = fixture_project()?;
        let setup = ProjectIndexer::new(&root, fixture.path().join("model"));
        let manifest = setup.index()?;
        let root_symbol = manifest
            .symbols
            .iter()
            .find(|symbol| symbol.name == "Root")
            .expect("fixture should include Root symbol");
        let vector_index = DeterministicVectorIndex::new(BTreeMap::from([(
            root_symbol.id.clone(),
            vec![1.0, 0.0],
        )]));
        let query = RetrievalQuery {
            text: Some("Root".to_string()),
            path: None,
            symbol: None,
            limit: 1,
            include_graph_expansion: false,
        };
        let actual = retrieve_with_boundaries(
            &manifest,
            &query,
            Some(&VectorQuery { embedding: vec![1.0, 0.0] }),
            Some(&vector_index),
            Some(&DeterministicReranker),
        );
        let expected = BTreeSet::from([
            "lexical".to_string(),
            "vector".to_string(),
            "rerank".to_string(),
        ]);
        assert_eq!(
            actual
                .first()
                .map(|result| result.score_parts.keys().cloned().collect::<BTreeSet<_>>())
                .expect("retrieval should return at least one fused result"),
            expected
        );
        Ok(())
    }
}
