pub struct BuiltInCommand {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub description: &'static str,
    pub action: &'static str,
    pub ret: bool,
}

pub const BUILT_IN_COMMANDS: &[BuiltInCommand] = &[
    BuiltInCommand { name: "new", aliases: &["n"], description: "Start new conversation", action: "_forge_action_new \"$input_text\"", ret: false },
    BuiltInCommand { name: "info", aliases: &["i"], description: "Print session information", action: "_forge_action_info", ret: false },
    BuiltInCommand { name: "dump", aliases: &["d"], description: "Save conversation as JSON or HTML (use /dump html for HTML format)", action: "_forge_action_dump \"$input_text\"", ret: false },
    BuiltInCommand { name: "compact", aliases: &[], description: "Compact the conversation context", action: "_forge_action_compact", ret: false },
    BuiltInCommand { name: "retry", aliases: &["r"], description: "Retry the last command", action: "_forge_action_retry", ret: false },
    BuiltInCommand { name: "agent", aliases: &["a"], description: "Select and switch between agents", action: "_forge_action_agent \"$input_text\"", ret: false },
    BuiltInCommand { name: "conversation", aliases: &["c"], description: "List all conversations for the active workspace", action: "_forge_action_conversation \"$input_text\"", ret: false },
    BuiltInCommand { name: "config-model", aliases: &["cm"], description: "Switch the models", action: "_forge_action_model \"$input_text\"", ret: false },
    BuiltInCommand { name: "model", aliases: &["m"], description: "Switch the model for the current session only, without modifying global config", action: "_forge_action_session_model \"$input_text\"", ret: false },
    BuiltInCommand { name: "config-reload", aliases: &["cr", "model-reset", "mr"], description: "Reset all session overrides (model, provider, reasoning effort) to use global config", action: "_forge_action_config_reload", ret: false },
    BuiltInCommand { name: "reasoning-effort", aliases: &["re"], description: "Set reasoning effort for the current session only", action: "_forge_action_reasoning_effort \"$input_text\"", ret: false },
    BuiltInCommand { name: "config-reasoning-effort", aliases: &["cre"], description: "Set the reasoning effort level in global config", action: "_forge_action_config_reasoning_effort \"$input_text\"", ret: false },
    BuiltInCommand { name: "config-commit-model", aliases: &["ccm"], description: "Set the model used for commit message generation", action: "_forge_action_commit_model \"$input_text\"", ret: false },
    BuiltInCommand { name: "config-suggest-model", aliases: &["csm"], description: "Set the model used for command suggestion generation", action: "_forge_action_suggest_model \"$input_text\"", ret: false },
    BuiltInCommand { name: "tools", aliases: &["t"], description: "List all available tools with their descriptions and schema", action: "_forge_action_tools", ret: false },
    BuiltInCommand { name: "config", aliases: &["env", "e"], description: "Display effective resolved configuration in TOML format", action: "_forge_action_config", ret: false },
    BuiltInCommand { name: "config-edit", aliases: &["ce"], description: "Open the global forge config file (~/forge/.forge.toml) in an editor", action: "_forge_action_config_edit", ret: false },
    BuiltInCommand { name: "skill", aliases: &[], description: "List all available skills", action: "_forge_action_skill", ret: false },
    BuiltInCommand { name: "edit", aliases: &["ed"], description: "Use an external editor to write a prompt", action: "_forge_action_editor \"$input_text\"", ret: true },
    BuiltInCommand { name: "commit", aliases: &[], description: "Directly commits AI generated commit message", action: "_forge_action_commit \"$input_text\"", ret: false },
    BuiltInCommand { name: "commit-preview", aliases: &[], description: "Previews AI generated commit message", action: "_forge_action_commit_preview \"$input_text\"", ret: true },
    BuiltInCommand { name: "suggest", aliases: &["s"], description: "Generate shell commands without executing them", action: "_forge_action_suggest \"$input_text\"", ret: true },
    BuiltInCommand { name: "clone", aliases: &[], description: "Clone and manage conversation context", action: "_forge_action_clone \"$input_text\"", ret: false },
    BuiltInCommand { name: "rename", aliases: &["rn"], description: "Rename the current conversation", action: "_forge_action_rename \"$input_text\"", ret: false },
    BuiltInCommand { name: "conversation-rename", aliases: &[], description: "Rename a conversation by ID or interactively", action: "_forge_action_conversation_rename \"$input_text\"", ret: false },
    BuiltInCommand { name: "copy", aliases: &[], description: "Copy last assistant message to clipboard as raw markdown", action: "_forge_action_copy", ret: false },
    BuiltInCommand { name: "workspace-sync", aliases: &["sync"], description: "Sync the current workspace for codebase search", action: "_forge_action_sync", ret: false },
    BuiltInCommand { name: "workspace-init", aliases: &["sync-init"], description: "Initialize a new workspace without syncing files", action: "_forge_action_sync_init", ret: false },
    BuiltInCommand { name: "workspace-status", aliases: &["sync-status"], description: "Show sync status of all workspace files", action: "_forge_action_sync_status", ret: false },
    BuiltInCommand { name: "workspace-info", aliases: &["sync-info"], description: "Show workspace information with sync details", action: "_forge_action_sync_info", ret: false },
    BuiltInCommand { name: "provider-login", aliases: &["login", "provider"], description: "Login to a provider", action: "_forge_action_login \"$input_text\"", ret: false },
    BuiltInCommand { name: "logout", aliases: &[], description: "Logout from a provider", action: "_forge_action_logout \"$input_text\"", ret: false },
    BuiltInCommand { name: "doctor", aliases: &[], description: "Run environment diagnostics for the shell plugin", action: "_forge_action_doctor", ret: false },
    BuiltInCommand { name: "keyboard-shortcuts", aliases: &["kb"], description: "Display ZSH keyboard shortcuts", action: "_forge_action_keyboard", ret: false },
    BuiltInCommand { name: "setup", aliases: &[], description: "Setup zsh integration by updating .zshrc", action: "forge setup", ret: false }, // wait, what was setup? Let's check dispatcher.zsh
];
